### ISSUE TITLE
Spawned at the middle of the ocean with weird glitches

### ISSUE THREAD

**Issue by ronrozenberg** [PixelGuys/Cubyz-Launcher#2]
When i open a world in the game it just spawns me at the bottom of the ocean, and i am running the latest version of java.
![‏‏צילום מסך (155)](https://user-images.githubusercontent.com/47514469/146769795-084cb8bf-7ed0-4ca6-8c5d-3e79c10af304.png)

**Comment by IntegratedQuantum** [comment]
The spawning under water is a known issue. Until I get it fixed, you can either try to climb out of there or create a new game and hope that you don't spawn under the ocean.

About the glitches: Seems like your graphics card is doing something unexpected I'll take a look at that.
